server:
  database:
    host: ${DATABASE_HOST:localhost}
    port: ${DATABASE_PORT:1433}
    name: ${DATABASE_NAME:master}
    user: ${DATABASE_USER:sa}
    passwd: ${DATABASE_PASSWORD:PasswordnyaSA2018}
    default-schema: ${DATABASE_SCHEMA:dbo}
spring:
  application:
    name: sales-routing
  mvc:
    dispatch-options-request: true
  datasource:
    url: jdbc:sqlserver://${server.database.host}:${server.database.port};databaseName=${server.database.name}
    username: ${server.database.user}
    password: ${server.database.passwd}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_catalog: ${server.database.name}
        default_schema: ${server.database.default-schema}
        format_sql: true
        enable_lazy_load_no_trans: true
        id:
          new_generator_mappings: false
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        globally_quoted_identifiers: true
        temp:
          use_jdbc_metadata_defaults: false
    database: sql_server
  flyway:
    encoding: UTF-8
    enabled: true
    baseline-on-migrate: true
    locations: classpath:/db/migration
    schemas: dbo
    clean-disabled: false
    clean-on-validation-error: true
    connect-retries: 3
logging:
  level:
    org.springframework: ERROR
    com.maryanto.dimas.example: ${LOG_LEVEL:DEBUG}
  file:
    name: ${LOG_LOCATION:${spring.application.name}.log}

